// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CategoriaAtividade string

const (
	CategoriaAtividadePalestra             CategoriaAtividade = "palestra"
	CategoriaAtividadeMinicurso            CategoriaAtividade = "minicurso"
	CategoriaAtividadeMesaRedonda          CategoriaAtividade = "mesa_redonda"
	CategoriaAtividadeOficina              CategoriaAtividade = "oficina"
	CategoriaAtividadeWorkshop             CategoriaAtividade = "workshop"
	CategoriaAtividadePainel               CategoriaAtividade = "painel"
	CategoriaAtividadeApresentacaoTrabalho CategoriaAtividade = "apresentacao_trabalho"
	CategoriaAtividadeAberturaEncerramento CategoriaAtividade = "abertura_encerramento"
)

func (e *CategoriaAtividade) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CategoriaAtividade(s)
	case string:
		*e = CategoriaAtividade(s)
	default:
		return fmt.Errorf("unsupported scan type for CategoriaAtividade: %T", src)
	}
	return nil
}

type NullCategoriaAtividade struct {
	CategoriaAtividade CategoriaAtividade
	Valid              bool // Valid is true if CategoriaAtividade is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCategoriaAtividade) Scan(value interface{}) error {
	if value == nil {
		ns.CategoriaAtividade, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CategoriaAtividade.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCategoriaAtividade) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CategoriaAtividade), nil
}

type StatusSpace string

const (
	StatusSpaceDisponivel StatusSpace = "disponivel"
	StatusSpaceReservado  StatusSpace = "reservado"
	StatusSpaceManutencao StatusSpace = "manutencao"
	StatusSpaceInativo    StatusSpace = "inativo"
)

func (e *StatusSpace) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusSpace(s)
	case string:
		*e = StatusSpace(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusSpace: %T", src)
	}
	return nil
}

type NullStatusSpace struct {
	StatusSpace StatusSpace
	Valid       bool // Valid is true if StatusSpace is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusSpace) Scan(value interface{}) error {
	if value == nil {
		ns.StatusSpace, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusSpace.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusSpace) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusSpace), nil
}

type TypeSpace string

const (
	TypeSpaceSalaDeAula  TypeSpace = "sala_de_aula"
	TypeSpaceLaboratorio TypeSpace = "laboratorio"
	TypeSpaceAuditorio   TypeSpace = "auditorio"
	TypeSpaceAreaExterna TypeSpace = "area_externa"
)

func (e *TypeSpace) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypeSpace(s)
	case string:
		*e = TypeSpace(s)
	default:
		return fmt.Errorf("unsupported scan type for TypeSpace: %T", src)
	}
	return nil
}

type NullTypeSpace struct {
	TypeSpace TypeSpace
	Valid     bool // Valid is true if TypeSpace is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypeSpace) Scan(value interface{}) error {
	if value == nil {
		ns.TypeSpace, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypeSpace.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypeSpace) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypeSpace), nil
}

type TypeUser string

const (
	TypeUserStudent   TypeUser = "student"
	TypeUserProfessor TypeUser = "professor"
	TypeUserEmployee  TypeUser = "employee"
)

func (e *TypeUser) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypeUser(s)
	case string:
		*e = TypeUser(s)
	default:
		return fmt.Errorf("unsupported scan type for TypeUser: %T", src)
	}
	return nil
}

type NullTypeUser struct {
	TypeUser TypeUser
	Valid    bool // Valid is true if TypeUser is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypeUser) Scan(value interface{}) error {
	if value == nil {
		ns.TypeUser, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypeUser.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypeUser) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypeUser), nil
}

type Activity struct {
	ID          pgtype.UUID
	Name        string
	DateStart   pgtype.Timestamp
	DateEnd     pgtype.Timestamp
	Category    CategoriaAtividade
	Description string
	IDEvent     pgtype.UUID
}

type Certificate struct {
	ID         pgtype.UUID
	TotalHours int32
	IssueDate  pgtype.Date
	IDEvent    pgtype.UUID
	IDStudent  pgtype.UUID
}

type Course struct {
	ID   pgtype.UUID
	Name string
}

type Employee struct {
	IDUser pgtype.UUID
}

type Equipment struct {
	ID          pgtype.UUID
	Name        string
	Description string
}

type EquipmentReservation struct {
	ID          pgtype.UUID
	IDEquipment pgtype.UUID
	IDUser      pgtype.UUID
	DateStart   pgtype.Timestamp
	DateEnd     pgtype.Timestamp
}

type Event struct {
	ID            pgtype.UUID
	Name          string
	DateStart     pgtype.Timestamp
	DateEnd       pgtype.Timestamp
	Description   string
	NameOrganizer string
}

type Professor struct {
	IDUser           pgtype.UUID
	CredentialNumber string
}

type ProfessorsCourse struct {
	ID          pgtype.UUID
	IDProfessor pgtype.UUID
	IDCourse    pgtype.UUID
}

type RegistrationsActivity struct {
	ID               pgtype.UUID
	RegistrationDate pgtype.Timestamp
	IDParticipant    pgtype.UUID
	IDActivity       pgtype.UUID
}

type RegistrationsEvent struct {
	ID               pgtype.UUID
	RegistrationDate pgtype.Timestamp
	IDParticipant    pgtype.UUID
	IDEvent          pgtype.UUID
}

type Space struct {
	ID     pgtype.UUID
	Name   string
	Type   TypeSpace
	Status StatusSpace
	Block  string
}

type SpaceReservation struct {
	ID        pgtype.UUID
	IDSpace   pgtype.UUID
	IDUser    pgtype.UUID
	DateStart pgtype.Timestamp
	DateEnd   pgtype.Timestamp
}

type Student struct {
	IDUser           pgtype.UUID
	EnrollmentNumber string
	IDCourse         pgtype.UUID
}

type User struct {
	ID                 pgtype.UUID
	Name               string
	PasswordHash       string
	InstitutionalEmail string
	UserType           TypeUser
}

type VwCompleteUser struct {
	ID                 pgtype.UUID
	UserName           string
	InstitutionalEmail string
	UserType           TypeUser
	EnrollmentNumber   pgtype.Text
	CourseName         pgtype.Text
	CredentialNumber   pgtype.Text
}

type VwUserActivityRegistration struct {
	RegistrationID     pgtype.UUID
	RegistrationDate   pgtype.Timestamp
	UserID             pgtype.UUID
	UserName           string
	InstitutionalEmail string
	ActivityID         pgtype.UUID
	ActivityName       string
	Category           CategoriaAtividade
	DateStart          pgtype.Timestamp
	DateEnd            pgtype.Timestamp
	EventName          string
}

type VwUserEventRegistration struct {
	RegistrationID     pgtype.UUID
	RegistrationDate   pgtype.Timestamp
	UserID             pgtype.UUID
	UserName           string
	InstitutionalEmail string
	EventID            pgtype.UUID
	EventName          string
	DateStart          pgtype.Timestamp
	DateEnd            pgtype.Timestamp
	NameOrganizer      string
}
