// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpaceReservation = `-- name: CreateSpaceReservation :one
INSERT INTO space_reservations (
    id, id_space, id_user, date_start, date_end
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, id_space, id_user, date_start, date_end
`

type CreateSpaceReservationParams struct {
	ID        pgtype.UUID
	IDSpace   pgtype.UUID
	IDUser    pgtype.UUID
	DateStart pgtype.Timestamp
	DateEnd   pgtype.Timestamp
}

func (q *Queries) CreateSpaceReservation(ctx context.Context, arg CreateSpaceReservationParams) (SpaceReservation, error) {
	row := q.db.QueryRow(ctx, createSpaceReservation,
		arg.ID,
		arg.IDSpace,
		arg.IDUser,
		arg.DateStart,
		arg.DateEnd,
	)
	var i SpaceReservation
	err := row.Scan(
		&i.ID,
		&i.IDSpace,
		&i.IDUser,
		&i.DateStart,
		&i.DateEnd,
	)
	return i, err
}
